package bkap.user.entity;
// Generated 24-Sep-2019 20:07:04 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * GroupProduct generated by hbm2java
 */
public class GroupProduct  implements java.io.Serializable {


     private String groupId;
     private String groupName;
     private String imageLink;
     private String descriptions;
     private Boolean groupStatus;
     private Set products = new HashSet(0);

    public GroupProduct() {
    }

	
    public GroupProduct(String groupId) {
        this.groupId = groupId;
    }
    public GroupProduct(String groupId, String groupName, String imageLink, String descriptions, Boolean groupStatus, Set products) {
       this.groupId = groupId;
       this.groupName = groupName;
       this.imageLink = imageLink;
       this.descriptions = descriptions;
       this.groupStatus = groupStatus;
       this.products = products;
    }
   
    public String getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public String getImageLink() {
        return this.imageLink;
    }
    
    public void setImageLink(String imageLink) {
        this.imageLink = imageLink;
    }
    public String getDescriptions() {
        return this.descriptions;
    }
    
    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions;
    }
    public Boolean getGroupStatus() {
        return this.groupStatus;
    }
    
    public void setGroupStatus(Boolean groupStatus) {
        this.groupStatus = groupStatus;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


