package bkap.user.entity;
// Generated 24-Sep-2019 20:07:04 by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private int menuId;
     private String menuName;
     private Boolean menuStatus;

    public Menu() {
    }

	
    public Menu(int menuId) {
        this.menuId = menuId;
    }
    public Menu(int menuId, String menuName, Boolean menuStatus) {
       this.menuId = menuId;
       this.menuName = menuName;
       this.menuStatus = menuStatus;
    }
   
    public int getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(int menuId) {
        this.menuId = menuId;
    }
    public String getMenuName() {
        return this.menuName;
    }
    
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }
    public Boolean getMenuStatus() {
        return this.menuStatus;
    }
    
    public void setMenuStatus(Boolean menuStatus) {
        this.menuStatus = menuStatus;
    }




}


