package bkap.user.entity;
// Generated 24-Sep-2019 20:07:04 by Hibernate Tools 4.3.1



/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail  implements java.io.Serializable {


     private OrderDetailId id;
     private Orders orders;
     private Product product;
     private Double amount;
     private Boolean orderDetailStatus;

    public OrderDetail() {
    }

	
    public OrderDetail(OrderDetailId id, Orders orders, Product product) {
        this.id = id;
        this.orders = orders;
        this.product = product;
    }
    public OrderDetail(OrderDetailId id, Orders orders, Product product, Double amount, Boolean orderDetailStatus) {
       this.id = id;
       this.orders = orders;
       this.product = product;
       this.amount = amount;
       this.orderDetailStatus = orderDetailStatus;
    }
   
    public OrderDetailId getId() {
        return this.id;
    }
    
    public void setId(OrderDetailId id) {
        this.id = id;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Boolean getOrderDetailStatus() {
        return this.orderDetailStatus;
    }
    
    public void setOrderDetailStatus(Boolean orderDetailStatus) {
        this.orderDetailStatus = orderDetailStatus;
    }




}


