package bkap.user.entity;
// Generated 24-Sep-2019 20:07:04 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import org.springframework.format.annotation.NumberFormat;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {

     private int orderId;

     private String customerName;
     
     private Double amount;
     private Integer quantity;

     private String addresss;
     

     private String email;

     private String phone;
     private int orderStatus;
     private String orderDate;
     private String listProduct;
     private Set orderDetails = new HashSet(0);

   
    public Orders() {
    }

	
    public Orders(int orderId) {
        this.orderId = orderId;
    }
    public Orders(int orderId, String customerName, Double amount, Integer quantity, String addresss, String email, String phone, int orderStatus, String orderDate,String listProduct,Set orderDetails) {
       this.orderId = orderId;
       this.customerName = customerName;
       this.amount = amount;
       this.quantity = quantity;
       this.addresss = addresss;
       this.email = email;
       this.phone = phone;
       this.orderStatus = orderStatus;
       this.orderDate = orderDate;
       this.orderDetails = orderDetails;
       this.listProduct =  listProduct;
    }

    
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
   
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public String getAddresss() {
        return this.addresss;
    }
    
    public void setAddresss(String addresss) {
        this.addresss = addresss;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public int getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(int orderStatus) {
        this.orderStatus = orderStatus;
    }
    public String getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate;
    }
    public String getListProduct() {
        return listProduct;
    }

    public void setListProduct(String listProduct) {
        this.listProduct = listProduct;
    }
    public Set getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Set orderDetails) {
        this.orderDetails = orderDetails;
    }




}


