package bkap.user.entity;
// Generated 24-Sep-2019 20:07:04 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int userId;
     private String userName;
     private String passW;
     private String email;
     private String addresss;
     private String phone;
     private Boolean userStatus;
     private Set orderses = new HashSet(0);

    public Users() {
    }

	
    public Users(int userId) {
        this.userId = userId;
    }
    public Users(int userId, String userName, String passW, String email, String addresss, String phone, Boolean userStatus, Set orderses) {
       this.userId = userId;
       this.userName = userName;
       this.passW = passW;
       this.email = email;
       this.addresss = addresss;
       this.phone = phone;
       this.userStatus = userStatus;
       this.orderses = orderses;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassW() {
        return this.passW;
    }
    
    public void setPassW(String passW) {
        this.passW = passW;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddresss() {
        return this.addresss;
    }
    
    public void setAddresss(String addresss) {
        this.addresss = addresss;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Boolean getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(Boolean userStatus) {
        this.userStatus = userStatus;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


